server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 1000M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 代理API请求到后端服务（注意：后端服务名在Docker Compose中定义为server）
    location /api/ {
        proxy_pass http://server:8000/;  # 后端容器的地址和端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}