"""add owner_id index

Revision ID: 5ff0d3a3b285
Revises: b5c7da498858
Create Date: 2026-03-04 00:09:40.920234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff0d3a3b285'
down_revision: Union[str, None] = 'b5c7da498858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_owner_id'), 'albums', ['owner_id'], unique=False)
    op.create_index(op.f('ix_photos_owner_id'), 'photos', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_owner_id'), table_name='photos')
    op.drop_index(op.f('ix_albums_owner_id'), table_name='albums')
    # ### end Alembic commands ###
